-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-11-27 09:32:07 ICT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c


-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE feedback
(
    id_revision      INTEGER  NOT NULL,
    revision_note    CLOB,
    revision_date    DATE     NOT NULL,
    proposals_id     CHAR(36) NOT NULL,
    user_id          INTEGER  NOT NULL,
    revision_section SMALLINT NOT NULL
)
    LOGGING;

ALTER TABLE feedback
    ADD CONSTRAINT feedback_pk PRIMARY KEY (id_revision);

CREATE TABLE lecture
(
    nip           VARCHAR2(18) NOT NULL,
    user_id       INTEGER NOT NULL,
    major         VARCHAR2(100) NOT NULL,
    study_program VARCHAR2(150) NOT NULL,
    status        VARCHAR2(20) NOT NULL
)
    LOGGING;

ALTER TABLE lecture
    ADD CHECK ( status IN ('AKTIF', 'NON-AKTIF') );

ALTER TABLE lecture
    ADD CONSTRAINT lecture_pk PRIMARY KEY (nip);

ALTER TABLE lecture
    ADD CONSTRAINT lecture_id_user_un UNIQUE (user_id);

CREATE TABLE proponent_members
(
    id           CHAR(36) NOT NULL,
    proposals_id CHAR(36) NOT NULL,
    students_nim VARCHAR2(9) NOT NULL,
    role         VARCHAR2(20) NOT NULL
)
    LOGGING;

ALTER TABLE proponent_members
    ADD CHECK ( role IN ('LEADER', 'MEMBER-1', 'MEMBER-2', 'MEMBER-3', 'MEMBER-4') );

ALTER TABLE proponent_members
    ADD CONSTRAINT proponent_members_pk PRIMARY KEY (id);

CREATE TABLE proposals
(
    id                 CHAR(36)           NOT NULL,
    lecture_nip        VARCHAR2(18) NOT NULL,
    scheme_types_id    CHAR(36)           NOT NULL,
    letter             VARCHAR2(255),
    team_name          VARCHAR2(60) NOT NULL,
    business_name      VARCHAR2(100) NOT NULL,
    business_overview  CLOB,
    business_instagram VARCHAR2(20),
    business_situation VARCHAR2(255) NOT NULL,
    submission_funds   NUMBER(15, 2) NOT NULL,
    turnover_targets   NUMBER(15, 2) NOT NULL,
    year               SMALLINT           NOT NULL,
    status             VARCHAR2(20) NOT NULL,
    is_completed       SMALLINT DEFAULT 0 NOT NULL
)
    LOGGING;

ALTER TABLE proposals
    ADD CHECK ( status IN ('DISETUJUI', 'DITOLAK', 'LOLOS', 'DIUSULKAN', 'DIVERIFIKASI', 'TIDAK_LOLOS',
                           'VERIFIKASI_GAGAL') );

ALTER TABLE proposals
    ADD CONSTRAINT proposals_pk PRIMARY KEY (id);

ALTER TABLE proposals
    ADD CONSTRAINT proposals_business_name_un UNIQUE (business_name);

CREATE TABLE reviewer
(
    id_reviewer CHAR(36) NOT NULL,
    user_id     INTEGER  NOT NULL,
    company     VARCHAR2(100),
    status      VARCHAR2(20) NOT NULL
)
    LOGGING;

ALTER TABLE reviewer
    ADD CHECK ( status IN ('AKTIF', 'NON-AKTIF') );

ALTER TABLE reviewer
    ADD CONSTRAINT reviewer_pk PRIMARY KEY (id_reviewer);

ALTER TABLE reviewer
    ADD CONSTRAINT reviewer_id_user_un UNIQUE (user_id);

CREATE TABLE scheme_types
(
    id         CHAR(36) NOT NULL,
    schemes_id CHAR(36) NOT NULL,
    name       VARCHAR2(100) NOT NULL
)
    LOGGING;

ALTER TABLE scheme_types
    ADD CONSTRAINT scheme_types_pk PRIMARY KEY (id);

CREATE TABLE schemes
(
    id   CHAR(36) NOT NULL,
    name VARCHAR2(10) NOT NULL
)
    LOGGING;

ALTER TABLE schemes
    ADD CONSTRAINT schemes_pk PRIMARY KEY (id);

CREATE TABLE students
(
    nim           VARCHAR2(9) NOT NULL,
    user_id       INTEGER  NOT NULL,
    major         VARCHAR2(100) NOT NULL,
    study_program VARCHAR2(150) NOT NULL,
    year          SMALLINT NOT NULL,
    status        VARCHAR2(20) NOT NULL
)
    LOGGING;

ALTER TABLE students
    ADD CHECK ( status IN ('AKTIF', 'NON-AKTIF') );

ALTER TABLE students
    ADD CONSTRAINT students_pk PRIMARY KEY (nim);

ALTER TABLE students
    ADD CONSTRAINT students_id_user_un UNIQUE (user_id);

CREATE TABLE support_files
(
    id           CHAR(36) NOT NULL,
    proposals_id CHAR(36) NOT NULL,
    name         VARCHAR2(50) NOT NULL,
    url          CLOB
)
    LOGGING;

ALTER TABLE support_files
    ADD CONSTRAINT support_files_pk PRIMARY KEY (id);

CREATE TABLE timeline_types
(
    id           CHAR(36) NOT NULL,
    timelines_id CHAR(36) NOT NULL,
    name         VARCHAR2(70) NOT NULL,
    order_num    NUMBER(3) CHECK (order_num > 0),
    start_date   DATE     NOT NULL,
    end          DATE     NOT NULL
)
    LOGGING;

ALTER TABLE timeline_types
    ADD CONSTRAINT timeline_types_pk PRIMARY KEY (id);

CREATE TABLE timelines
(
    id         CHAR(36) NOT NULL,
    schemes_id CHAR(36) NOT NULL,
    year       SMALLINT NOT NULL,
    status     VARCHAR2(20) NOT NULL
)
    LOGGING;

ALTER TABLE timelines
    ADD CHECK ( status IN ('AKTIF', 'NON-AKTIF') );

ALTER TABLE timelines
    ADD CONSTRAINT timelines_pk PRIMARY KEY (id);

CREATE TABLE "user"
(
    id_user  INTEGER NOT NULL,
    name     VARCHAR2(100) NOT NULL,
    phone    VARCHAR2(15) NOT NULL,
    email    VARCHAR2(100) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    role     VARCHAR2(20) NOT NULL
)
    LOGGING;

ALTER TABLE "user"
    ADD CHECK ( role IN ('admin', 'lecture', 'reviewer', 'student') );

ALTER TABLE "user"
    ADD CONSTRAINT user_pk PRIMARY KEY (id_user);

ALTER TABLE "user"
    ADD CONSTRAINT user_email_un UNIQUE (email);

ALTER TABLE feedback
    ADD CONSTRAINT feedback_proposals_fk FOREIGN KEY (proposals_id)
        REFERENCES proposals (id)
        NOT DEFERRABLE;

ALTER TABLE feedback
    ADD CONSTRAINT feedback_user_fk FOREIGN KEY (user_id)
        REFERENCES "user" (id_user)
        NOT DEFERRABLE;

ALTER TABLE lecture
    ADD CONSTRAINT lecture_user_fk FOREIGN KEY (user_id)
        REFERENCES "user" (id_user)
        NOT DEFERRABLE;

ALTER TABLE proponent_members
    ADD CONSTRAINT proponent_members_proposals_fk FOREIGN KEY (proposals_id)
        REFERENCES proposals (id)
        NOT DEFERRABLE;

ALTER TABLE proponent_members
    ADD CONSTRAINT proponent_members_students_fk FOREIGN KEY (students_nim)
        REFERENCES students (nim)
        NOT DEFERRABLE;

ALTER TABLE proposals
    ADD CONSTRAINT proposals_lecture_fk FOREIGN KEY (lecture_nip)
        REFERENCES lecture (nip)
        NOT DEFERRABLE;

ALTER TABLE proposals
    ADD CONSTRAINT proposals_scheme_types_fk FOREIGN KEY (scheme_types_id)
        REFERENCES scheme_types (id)
        NOT DEFERRABLE;

ALTER TABLE reviewer
    ADD CONSTRAINT reviewer_user_fk FOREIGN KEY (user_id)
        REFERENCES "user" (id_user)
        NOT DEFERRABLE;

ALTER TABLE scheme_types
    ADD CONSTRAINT scheme_types_schemes_fk FOREIGN KEY (schemes_id)
        REFERENCES schemes (id)
        NOT DEFERRABLE;

ALTER TABLE students
    ADD CONSTRAINT students_user_fk FOREIGN KEY (user_id)
        REFERENCES "user" (id_user)
        NOT DEFERRABLE;

ALTER TABLE support_files
    ADD CONSTRAINT support_files_proposals_fk FOREIGN KEY (proposals_id)
        REFERENCES proposals (id)
        NOT DEFERRABLE;

ALTER TABLE timeline_types
    ADD CONSTRAINT timeline_types_timelines_fk FOREIGN KEY (timelines_id)
        REFERENCES timelines (id)
        NOT DEFERRABLE;

ALTER TABLE timelines
    ADD CONSTRAINT timelines_schemes_fk FOREIGN KEY (schemes_id)
        REFERENCES schemes (id)
        NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             37
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0
